spring.datasource.url=jdbc:postgresql://localhost:5432/siscetran
spring.datasource.username=postgres
spring.datasource.password=andre123
spring.datasource.driver-class-name=org.postgresql.Driver

# Como o schema já foi criado manualmente via SQL, não deixe o Hibernate recriar as tabelas:
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true